name: 'SSH to Actions'
author: 'Hosh Sadiq'
description: 'Connect to GitHub Actions VM via SSH for interactive debugging'
runs:
  using: "composite"
  steps: 
    - run: $GITHUB_ACTION_PATH/ngrok2actions.sh
      shell: bash
branding:
  icon: 'terminal'
  color: 'gray-dark'
